uploads = []
outputs = []

[[generated]]
id = "F8T0joJHjF7zOQF0imTns"
uri = "file://Frontend/artifacts/fde-campus/public/images/mentor-7.png"
type = "image"
title = "generated_image"

[[generated]]
id = "uiTfzUFmhEaghOgHuIFsy"
uri = "file://Frontend/artifacts/fde-campus/public/images/mentor-nisha.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NIi-gPFrS8CIU90bIN8tf"
uri = "file://Frontend/artifacts/fde-campus/public/images/mentor-chitrangda.png"
type = "image"
title = "generated_image"

[[generated]]
id = "krMSB4HZRejXny1PG-u8S"
uri = "file://Frontend/artifacts/fde-campus/public/images/mentor-sai.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2vVa5-F_nEhLcDfGy9DTh"
uri = "file://Frontend/artifacts/fde-campus/public/images/mentor-krishna.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Ml0OYJT1eAUa43UqaS7tS"
uri = "file://Frontend/artifacts/fde-campus/public/images/mentor-asfiya.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Caj3wdoUNuRKU1lwI8ULg"
uri = "file://Frontend/artifacts/fde-campus/public/images/mentor-raksha.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VZvgk_Mp9Eb8DIZAkBKxt"
uri = "file://Frontend/artifacts/fde-campus/public/images/mentor-kalpana.png"
type = "image"
title = "generated_image"
